services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ["bash", "-lc", "rm -f tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0 -p 3000"]
    ports:
      - "3000:3000"
    volumes:
      - ./:/rails:cached
      - ./storage:/rails/storage
    environment:
      RAILS_ENV: development
      NODE_ENV: development
      BUNDLE_FROZEN: "false"
      REDIS_URL: redis://redis:6379/1
      RAILS_LOG_TO_STDOUT: "true"
      LISTEN_GEM_DEBUGGING: "true"
    working_dir: /rails
    depends_on:
      - redis
    tty: true
    stdin_open: true

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
