version: "3.9"

services:
<<<<<<< HEAD
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/rails
      - /var/run/docker.sock:/var/run/docker.sock  # <-- allow Docker inside container
=======
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ["bash", "-lc", "rm -f tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0 -p 3000"]
    ports:
      - "3000:3000"
    volumes:
      - ./:/rails:cached
      - ./storage:/rails/storage
>>>>>>> john-navbar-fix
    environment:
      - RAILS_ENV=development
    command: ./bin/rails server -b 0.0.0.0 -p 3000
    depends_on:
      - db
    privileged: true
    
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: rails
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rails_development
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
