version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/rails
      - /var/run/docker.sock:/var/run/docker.sock  # <-- allow Docker inside container
    environment:
      - RAILS_ENV=development
    command: ./bin/rails server -b 0.0.0.0 -p 3000
    depends_on:
      - db
    privileged: true
    
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: rails
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rails_development
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
